### ISSUE TITLE
How to call EFcore add data EF.Functions

### ISSUE THREAD

**Issue by l2999019** [tkhadimullin/ef-core-custom-functions#6]
like this 
EFContext.Models.Add(
new model{
1,
a=EF.Functions.DecryptByKey("TestPassword","Encrypted with Passphrapse")
})

I want to get the SQL statement
INSERT [dbo].[Models] (, [Encrypted], ]) 
VALUES (
	1, 
	ENCRYPTBYPASSPHRASE('TestPassword', 'Encrypted with Passphrapse'))

But it doesn't work

**Comment by tkhadimullin** [comment]
can you elaborate a bit more? maybe fork and provide a code sample that i can build?
