### ISSUE TITLE
When update to Entity Framework packages to 6.0.2, project not working.

### ISSUE THREAD

**Issue by iozcelik** [tkhadimullin/ef-core-custom-functions#8]
When update to Entity Framework packages to 6.0.2, project not working.

**Comment by tkhadimullin** [comment]
Can you provide a bit more detail on what branch you upgraded and what error message did you get?

**Comment by iozcelik** [comment]
I updated feature/ef-6.0-dbfunction branch. Actually you using rc2, if you try to change, also you get error.

**Comment by iozcelik** [comment]
I change TryAddScoped to AddScoped at my own project and it works. There is an issue with TryAddScoped. [https://github.com/dotnet/efcore/issues/27566](issue)

**Comment by tkhadimullin** [comment]
thank you for reporting it. 
I'll update it in due course or feel free to submit a PR - would be hugely appreciated
